export type Styles = {
  'actionBar': string;
  'actionButton': string;
  'actionsRow': string;
  'alertError': string;
  'barcodeGraphic': string;
  'barcodeGraphicLargeSel': string;
  'configControlsColumn': string;
  'configExampleBox': string;
  'configExampleCard': string;
  'configLayout': string;
  'encodedValue': string;
  'encodedValueLargeSel': string;
  'exportSurface': string;
  'fieldLabel': string;
  'formStack': string;
  'generateButton': string;
  'labelAppRoot': string;
  'labelBox': string;
  'labelBoxLargeSel': string;
  'labelDiv': string;
  'labelText': string;
  'largeSelHeading': string;
  'largeSelHeadingFallback': string;
  'largeSelHeadingMain': string;
  'largeSelHeadingPrefix': string;
  'largeSelHeadingSuffix': string;
  'largeSelLabelTextArea': string;
  'loaderBox': string;
  'panel': string;
  'panelTitle': string;
  'pdfDiv': string;
  'previewPage': string;
  'primaryCode': string;
  'printLabelDiv': string;
  'printPage': string;
  'printPortal': string;
  'secondaryCode': string;
  'sectionBox': string;
  'sectionIntro': string;
  'sectionTitle': string;
  'tabButton': string;
  'tabButtonActive': string;
  'tabList': string;
  'tabPanelBox': string;
  'tabPanelContent': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
